name: Deploy to server

env:
  DEPLOY_PATH: dragon3dgraff.ru/public_html/KnowItAll
  BUILD_SCRIPT_OUTPUT: dist

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.20.x
      # Записываем в переменные окружения имя текущей ветки
      # Чтобы избежать конфиликтов с URL, меняем точки на _, а слеши на минусы
      - name: Get branch name
        shell: bash
        run: echo "name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g' | sed 's/\./_/g')" >> $GITHUB_ENV
      # Устанавливаем зависимости для сборки
      - name: Install Dependencies
        run: npm i
      # Собираем приложение
      - name: Build Application
        run: npm run build

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          key: ${{ secrets.DEPLOY_SERVER_KEY }}
          source: ${{ env.BUILD_SCRIPT_OUTPUT }}
          target: ${{ env.DEPLOY_PATH }}
          rm: true
          strip_components: 1

      - name: Print Info
        run: echo "Deployed to dragon3dgraff.ru/public_html/KnowItAll"
